apiVersion: v1
kind: Service
metadata:
  name: stream-enricher
  namespace: cascade-system
  labels:
    app: stream-enricher
spec:
  type: ClusterIP
  selector:
    app: stream-enricher
  ports:
    - name: http
      port: 8001
      targetPort: http
