apiVersion: v1
kind: Service
metadata:
  name: feature-extractor-service
  namespace: cascade-system
  labels:
    app: feature-extractor-service
spec:
  type: ClusterIP
  selector:
    app: feature-extractor-service
  ports:
    - name: http
      port: 8013
      targetPort: http

