apiVersion: v1
kind: Service
metadata:
  name: autopilot-service
  namespace: cascade-system
  labels:
    app: autopilot-service
spec:
  selector:
    app: autopilot-service
  ports:
    - name: http
      port: 8024
      targetPort: http
