from __future__ import annotations

FEATURE_KEYS = [
    "event_count",
    "unhealthy_count",
    "healthy_count",
    "restart_signal_count",
    "warning_count",
    "error_count",
    "experiment_event_count",
    "incident_context_count",
    "avg_cpu",
    "max_cpu",
    "avg_memory",
    "max_memory",
    "avg_latency_ms",
    "max_latency_ms",
    "latency_p50_ms",
    "latency_p95_ms",
    "latency_p99_ms",
    "request_rate",
    "error_rate",
    "restart_rate",
    "unhealthy_rate",
    "readiness_rate",
    "availability_rate",
    "warning_event_count",
    "missing_metric_count",
    "dependency_unhealthy_count",
]
