apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cascade-targets-deny-cascade-system-egress
  namespace: cascade-targets
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                  - cascade-system
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
