apiVersion: v1
kind: Service
metadata:
  name: command-center-api
  namespace: cascade-system
  labels:
    app: command-center-api
spec:
  selector:
    app: command-center-api
  ports:
    - name: http
      port: 8031
      targetPort: http
