apiVersion: v1
kind: Service
metadata:
  name: chaos-planner-service
  namespace: cascade-system
  labels:
    app: chaos-planner-service
spec:
  selector:
    app: chaos-planner-service
  ports:
    - name: http
      port: 8019
      targetPort: http
