apiVersion: v1
kind: Service
metadata:
  name: experiment-tracker-service
  namespace: cascade-system
  labels:
    app: experiment-tracker-service
spec:
  type: ClusterIP
  selector:
    app: experiment-tracker-service
  ports:
    - name: http
      port: 8002
      targetPort: http
