apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-data
  namespace: cascade-system
  labels:
    app: redpanda
    cascade.io/state: durable
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
