apiVersion: v1
kind: Service
metadata:
  name: anomaly-detector-service
  namespace: cascade-system
  labels:
    app: anomaly-detector-service
spec:
  type: ClusterIP
  selector:
    app: anomaly-detector-service
  ports:
    - name: http
      port: 8014
      targetPort: http
