apiVersion: v1
kind: Service
metadata:
  name: telemetry-archiver
  namespace: cascade-system
  labels:
    app: telemetry-archiver
spec:
  type: ClusterIP
  selector:
    app: telemetry-archiver
  ports:
    - name: http
      port: 8010
      targetPort: http

