apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-cartservice-once
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - cascade-targets
    labelSelectors:
      app: cartservice
  duration: "30s"