apiVersion: v1
kind: Service
metadata:
  name: command-center
  namespace: cascade-system
  labels:
    app: command-center
spec:
  selector:
    app: command-center
  ports:
    - name: http
      port: 8030
      targetPort: http
